name             'resource-manager'
maintainer       'Vic Iglesias'
maintainer_email 'viglesiasce@gmail.com'
license          'Apache 2'
description      'Installs/Configures resource-manager'
long_description 'Installs/Configures resource-manager'
version          '0.1.0'
depends          'mongodb'
depends          'supervisor'
depends          'python'
