name             'resource-manager'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures resource-manager'
long_description 'Installs/Configures resource-manager'
version          '0.1.0'
depends          'mongodb'
depends          'supervisor'
depends          'python'
